AWSTemplateFormatVersion: '2010-09-09'
Description: 'Simple CloudFront distribution with an S3 origin'

Parameters:
  ProjectName:
    Type: String

Resources:
  WebApplicationStore:
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: 'Delete'
    Metadata:
      Comment: 'Bucket to store Delicious-Sandwich web app'
    Properties:
      AccessControl: 'Private'
      BucketName: !Ref ProjectName
      Tags:
        - Key: project
          Value: !Ref ProjectName

  WebApplicationStorePermission:
    Type: 'AWS::S3::BucketPolicy'
    Metadata:
      Comment: 'Bucket policy to allow cloudfront to access the data'
    Properties:
      Bucket: !Ref WebApplicationStore
      PolicyDocument:
        Statement:
          - Action:
              - 's3:GetObject'
            Effect: 'Allow'
            Principal:
              CanonicalUser: !GetAtt CfOriginAccessIdentity.S3CanonicalUserId
            Resource:
              - !Sub 'arn:aws:s3:::${WebApplicationStore}/*'


  CfDistribution:
    Type: 'AWS::CloudFront::Distribution'
    Metadata:
      Comment: 'A simple CloudFront distribution for Delicious-Sandwich web app'
    Properties:
      DistributionConfig:
        Comment: 'A simple distribution for Delicious-Sandwich web app'
        DefaultCacheBehavior:
          AllowedMethods:
            - 'HEAD'
            - 'GET'
          CachedMethods:
            - 'HEAD'
            - 'GET'
          Compress: false
          DefaultTTL: 86400
          ForwardedValues:
            Cookies:
              Forward: 'none'
            Headers:
              - 'Origin'
            QueryString: false
          MaxTTL: 31536000
          MinTTL: 86400
          TargetOriginId: !Sub 's3-origin-${WebApplicationStore}'
          ViewerProtocolPolicy: 'allow-all'
        DefaultRootObject: 'index.html'
        Enabled: true
        HttpVersion: 'http1.1'
        IPV6Enabled: false
        Origins:
          - DomainName: !GetAtt WebApplicationStore.DomainName
            Id: !Sub 's3-origin-${WebApplicationStore}'
            OriginPath: ''
            S3OriginConfig:
              OriginAccessIdentity: !Sub 'origin-access-identity/cloudfront/${CfOriginAccessIdentity}'
        PriceClass: 'PriceClass_All'

  CfOriginAccessIdentity:
    Metadata:
      Comment: 'Access S3 bucket content only through CloudFront'
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: 'Access S3 bucket content only through CloudFront'
    Type: 'AWS::CloudFront::CloudFrontOriginAccessIdentity'

Outputs:
  CfDistributionDomainName:
    Description: 'Domain name for Delicious-Sandwich cloudfront distrib'
    Value: !GetAtt CfDistribution.DomainName